### ISSUE TITLE
git_version.h missing while installation running

### ISSUE THREAD

**Issue by jtauscher** [mill1000/raspdif#16]
```
source/main.c:12:10: fatal error: 'git_version.h' file not found
#include "git_version.h"
         ^~~~~~~~~~~~~~~
1 error generated.

```

**Comment by mill1000** [comment]
Yeah I encountered this myself today. The Makefile was kinda messed up.

I pushed an update (8508b59) this morning to address it. Have you pulled that?

**Comment by jtauscher** [comment]
no, just any from the web - I'm a noob (kindof)

**Comment by mill1000** [comment]
Well try grabbing a fresh copy and let me know if the issue still persists

**Comment by jtauscher** [comment]
installation is running, but still not able to play via aplay or mpc play.
Only thing that works is 
`ffmpeg -i "..." -f s16le -acodec pcm_s16le - | sudo raspdif`

**Comment by mill1000** [comment]
Ok we can continue debugging that in #12. I'll close this one now.
